ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

test_configurations =
[
    {
        :suite_name   => 'system_tests1',
        :tests_to_run => 'cosmo_tester/test_suites/test_blueprints/hello_world_bash_test.py:HelloWorldBashTest.test_hello_world_on_ubuntu'
    }
]

def vagrant_configure(test_configurations)
  Vagrant.configure('2') do |config|
    config.vm.provider 'docker' do |d|
      d.build_dir = '.'
      d.build_args = ['-t', 'cloudify/test:env']
      d.cmd = ['/vagrant/system_tests.sh']
    end
    test_configurations.each do |test_config|
      suite_name = test_config[:suite_name]
      config.vm.define suite_name do |suite|
        suite.vm.provider 'docker' do |d|
          d.name = suite_name
          d.env = build_env(test_config)
        end
      end
    end
  end
end

def build_env(test_config)
    env_variable_names = ENV['CLOUDIFY_ENVIRONMENT_VARIABLE_NAMES'] || ''
    env_variable_names = env_variable_names.split(':')
    cloudify_env = {}
    env_variable_names.each do |name|
        if ENV[name]
            cloudify_env[name] = ENV[name]
        end
    end
    cloudify_env['RESOURCE_PREFIX'] = test_config[:suite_name] + '-'
    cloudify_env['NOSETESTS_TO_RUN'] = test_config[:tests_to_run]
    cloudify_env
end

vagrant_configure(test_configurations)
