########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

BASE_UBUNTU_BOX_NAME = 'precise64'
BASE_UBUNTU_BOX_URI = 'http://files.vagrantup.com/precise64.box'

# general
VIRTUALENV = 'cloudify'
BLUEPRINTS = 'blueprints'

# provider paths
EXOSCALE = 'exoscale'

Vagrant.configure('2') do |config|

  config.vm.define :cloudify do |cloudify|

    cloudify_ip = '10.0.0.2'

    cloudify.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    cloudify.vm.box = BASE_UBUNTU_BOX_NAME
    cloudify.vm.box_url = BASE_UBUNTU_BOX_URI
    cloudify.vm.network :private_network, ip: cloudify_ip
    cloudify.vm.hostname = 'cloudify'
    # cloudify.vm.synced_folder "../cloudify/examples", "/home/vagrant/examples", create: true
    command = """
      echo bootstrapping...

      # update
      echo updating db
      sudo apt-get -y update &&

      # install prereqs
      echo installing prerequisites
      sudo apt-get install -y python-setuptools python-dev vim
      sudo apt-get purge pip
      sudo easy_install -U pip
      sudo wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python

      # go home
      cd ~

      # virtualenv
      echo installing virtualenv
      sudo pip install virtualenv==1.11.4
      sudo pip install virtualenvwrapper
      # echo 'source /usr/local/bin/virtualenvwrapper.sh' >> /home/vagrant/.bashrc
      # source /usr/local/bin/virtualenvwrapper.sh
      echo creating #{VIRTUALENV} virtualenv
      # mkvirtualenv cloudify
      # workon cloudify
      virtualenv #{VIRTUALENV}
      source #{VIRTUALENV}/bin/activate

      # install cli
      echo installing cli and provider
      pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/master.zip --process-dependency-links

      # install exoscale provider
      pip install https://github.com/cloudify-cosmo/cloudify-cloudstack-provider/archive/master.zip --process-dependency-links
      # fix libclouds bug
      sed -i 's/publicKey/publickey/g' #{VIRTUALENV}/lib/python2.7/site-packages/libcloud/compute/drivers/cloudstack.py
      sed -i 's/privateKey/privatekey/g' #{VIRTUALENV}/lib/python2.7/site-packages/libcloud/compute/drivers/cloudstack.py
      mkdir -p ~/#{EXOSCALE}

      # deploy exoscale blueprints
      cd ~
      echo deploying nodecellar blueprint
      wget https://github.com/cloudify-cosmo/cloudify-nodecellar-cloudstack/archive/master.tar.gz
      mkdir -p ~/#{EXOSCALE}/#{BLUEPRINTS}
      tar -C ~/#{EXOSCALE}/#{BLUEPRINTS} -xzvf master.tar.gz
      rm master.tar.gz

      # add cfy bash completion
      activate_cfy_bash_completion

      echo bootstrap done.
      echo please run source ~/#{VIRTUALENV}/bin/activate to activate the virtualenv
      echo you can then run cfy --help to see a list of commands you can run.

      # exoscale specific
      echo you can also cd to ~/#{EXOSCALE}/#{BLUEPRINTS} where a blueprint awaits you
      """
    cloudify.vm.provision :shell do |sh|
      sh.privileged = false
      sh.inline = command
    end

  end

end