require 'json'
require 'yaml'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

def vagrant_configure
  Vagrant.configure('2') do |config|
    config.vm.provider 'docker' do |d|
      d.build_dir = '.'
      d.build_args = ['-t', 'cloudify/test:env']
      d.cmd = ['/vagrant/system_tests.sh']
    end
    full_suites_yaml = load_suites_yaml()
    full_suites_yaml['test_suites'].each do |suite_name, suite|
      config.vm.define suite_name do |container|
        container.vm.provider 'docker' do |d|
          d.name = suite_name
          d.env = build_env(full_suites_yaml, suite_name, suite)
        end
      end
    end
  end
end

def load_suites_yaml
  suites_path = ENV['TEST_SUITES_PATH']
  YAML.load_file(suites_path)
end

def build_env(full_suites_yaml, suite_name, suite)
    env_variable_names = ENV['CLOUDIFY_ENVIRONMENT_VARIABLE_NAMES'] || ''
    env_variable_names = env_variable_names.split(':')
    cloudify_env = {}
    env_variable_names.each do |name|
        if ENV[name]
            cloudify_env[name] = ENV[name]
        end
    end
    cloudify_env['TEST_SUITES_YAML'] = full_suites_yaml.to_json
    cloudify_env['TEST_SUITE_NAME'] = suite_name
    cloudify_env['TEST_SUITE'] = suite.to_json
    cloudify_env
end

vagrant_configure()
