require 'json'
require 'yaml'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

def vagrant_configure
  Vagrant.configure('2') do |config|
    config.vm.provider 'docker' do |d|
      d.build_dir = '.'
      d.build_args = ['-t', 'cloudify/test:env']
      d.cmd = ['/vagrant/suite_runner.sh']
    end
    suites_yaml = load_suites_yaml()
    suites_yaml['test_suites'].each do |suite_name, suite|
      config.vm.define suite_name do |container|
        container.vm.provider 'docker' do |d|
          d.name = suite_name
          d.env = build_env(suite_name, suite, suites_yaml)
        end
      end
    end
  end
end

def load_suites_yaml
  suites_path = ENV['TEST_SUITES_PATH']
  YAML.load_file(suites_path)
end

def build_env(suite_name, suite, suites_yaml)
    {
        'TEST_SUITE_NAME' => suite_name,
        'TEST_SUITE' => suite.to_json,
        'TEST_SUITES_VARIABLES' => (suites_yaml['variables'] || {}).to_json
    }
end

vagrant_configure()
